version: '3'

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    container_name:  zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: docker.io/bitnami/kafka:3.4
    container_name:  kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper


  kafka-ui0:
    image: provectuslabs/kafka-ui
    container_name:  kafka-ui
    ports:
      - "9094:8080"
    depends_on:
      - kafka
      - zookeeper
    restart: always
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181


  mongo:
    image: mongo:5.0.3-focal
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - /home/lelouch/Source/data/pedidos/mongo:/data/db
    

  postgre:
    image: postgres:12.9-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - /home/lelouch/Source/data/pedidos/pgsql:/var/lib/postgresql/data
